name                "ruby"
description         "Installs ruby"
long_description    IO.read(File.join(File.dirname(__FILE__), 'README.markdown'))
version             "1.0.0"
license             "MIT"
depends             "apt"
provides            "ruby"
recipe              "ruby", "Installs ruby"
supports            "ubuntu"
maintainer          "Jeremy Seago"
maintainer_email    "seagoj@gmail.com"
