name                "ruby"
version             "1.0.0"
license             "MIT"
depends             "apt"
provides            "ruby"
recipe              "ruby", "Installs ruby"
supports            "ubuntu"
maintainer          "Jeremy Seago"
maintainer_email    "seagoj@gmail.com"
